name: Deploy Website to Hosting

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync to Hosting via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # server-dir: /public_html/  # Uncomment and adjust if your host root directory is public_html